language: cpp

before_install:
  - sudo apt-add-repository ppa:neon/kf5
  - sudo apt-get update -qq
  - sudo apt-get install -y project-neon-libkdegames libboost-all-dev

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
